# Generated by Django 3.2 on 2021-05-07 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('synonym', models.CharField(max_length=250)),
                ('duration', models.IntegerField()),
                ('score', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Premiered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musim', models.CharField(choices=[('Spring', 'SPRING'), ('Summer', 'SUMMER'), ('Fall', 'FALL'), ('Winter', 'WINTER')], default='Spring', max_length=250)),
                ('tahun', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Ongoing', 'ONGOING'), ('Complete', 'COMPLETE')], default='Ongoing', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AnimeGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downloads.anime')),
                ('genreId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downloads.genre')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='premier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downloads.premiered'),
        ),
        migrations.AddField(
            model_name='anime',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downloads.series'),
        ),
        migrations.AddField(
            model_name='anime',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downloads.status'),
        ),
        migrations.AddField(
            model_name='anime',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downloads.studio'),
        ),
        migrations.AddField(
            model_name='anime',
            name='type_anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downloads.type'),
        ),
    ]
