# Generated by Django 3.2 on 2021-05-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='sinopsis',
            field=models.TextField(default=''),
        ),
    ]
