# Generated by Django 3.2.2 on 2021-05-08 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0002_anime_sinopsis'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='image',
            field=models.ImageField(default='', upload_to='static/covers/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='sampul',
            field=models.ImageField(default=None, upload_to='static/sampul/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ResolusiDownloads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolusi', models.CharField(max_length=10)),
                ('episodeAnimeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downloads.episodeanime')),
            ],
        ),
        migrations.CreateModel(
            name='LayananDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layanan', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=250)),
                ('resolusiDownloadId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downloads.resolusidownloads')),
            ],
        ),
        migrations.AddField(
            model_name='episodeanime',
            name='animeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downloads.anime'),
        ),
    ]
