# Generated by Django 3.2.2 on 2021-05-08 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0003_auto_20210508_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolusidownloads',
            name='animeId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='downloads.anime'),
            preserve_default=False,
        ),
    ]
