# Generated by Django 3.2.2 on 2021-05-08 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0004_resolusidownloads_animeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='layanandownload',
            name='animeId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='downloads.anime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layanandownload',
            name='episodeAnimeId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='downloads.episodeanime'),
            preserve_default=False,
        ),
    ]
