# Generated by Django 3.2.2 on 2021-05-08 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0006_layanan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layanandownload',
            name='layanan',
        ),
        migrations.AddField(
            model_name='layanandownload',
            name='layananId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='downloads.layanan'),
            preserve_default=False,
        ),
    ]
